### ISSUE TITLE
作者你好，请问cookie是怎么获取，另外能实现上传的接口吗？

### ISSUE THREAD

**Issue by jojowhoooo** [bingsanyu/feishu_minutes#1]

**Comment by bingsanyu** [comment]
cookie和token的获取在代码里有提到。

第一组是妙记的cookie和token，在飞书妙计主页https://**你的企业域名**.feishu.cn/minutes/home，按F12打开开发者工具，点击“网络”，然后刷新页面，找到下图中的请求并点击，找到这两个参数对应的值填入代码中即可。
![image](https://github.com/bingsanyu/feishumiaoji/assets/66949416/0b373b3f-0cb5-49ee-8b3a-e2f546e9d28e)

第二组是额度的cookie和token，在飞书管理后台页面https://**你的企业域名**.feishu.cn/admin/billing/equity-data按F12，步骤和第一组相同。其所对应的请求如下图。
![image](https://github.com/bingsanyu/feishumiaoji/assets/66949416/3b971c66-27cf-4a4d-8ddf-b401e037355f)

当然，如果你没有管理权限或者只是想单次下载，就不需要获取第二组参数，删除额度查询相关代码即可。

**Comment by bingsanyu** [comment]
上传文件没有研究过，妙记网页上传不是挺方便的嘛。难道是想要上传后下载并删除，实现无限白嫖语音转文字O.o？

**Comment by jojowhoooo** [comment]
> 上传文件没有研究过，妙记网页上传不是挺方便的嘛。难道是想要上传后下载并删除，实现无限白嫖语音转文字O.o？

被你发现了...我希望实现一个自动化，自动录制、上传（白嫖）语音转文字、下载视频带字幕、上传阿里云盘、alist查看

**Comment by bingsanyu** [comment]
> > 上传文件没有研究过，妙记网页上传不是挺方便的嘛。难道是想要上传后下载并删除，实现无限白嫖语音转文字O.o？
> 
> 被你发现了...我希望实现一个自动化，自动录制、上传（白嫖）语音转文字、下载视频带字幕、上传阿里云盘、alist查看 

我试了下，完全可行🤐
