### ISSUE TITLE
请问这个cookie 怎么填写

### ISSUE THREAD

**Issue by Huxzhi** [bingsanyu/feishu_minutes#2]
<img width="804" alt="image" src="https://github.com/bingsanyu/feishu_minutes/assets/49866441/0f13297b-dc92-44c9-bb5d-58306194f4eb">

是这样吗 

返回结果
<img width="804" alt="image" src="https://github.com/bingsanyu/feishu_minutes/assets/49866441/f1f0b435-eae0-477c-a03f-e10bbd0c19fd">

**Comment by bingsanyu** [comment]
![image](https://github.com/bingsanyu/feishu_minutes/assets/66949416/fde86caf-064c-46f1-ac15-f65ed5e58730)
cookie是这一大串。

**Comment by bingsanyu** [comment]
妙记cookie是以 _minutes_csrf_token=_ 开头的一大串：
![image](https://github.com/bingsanyu/feishu_minutes/assets/66949416/9216247f-77db-4354-9587-66a66ab6cecf)

**Comment by Huxzhi** [comment]
感谢
