### ISSUE TITLE
批量上传 不行啊 ,下载也挂了.

### ISSUE THREAD

**Issue by kiloppertry** [bingsanyu/feishu_minutes#3]
批量上传 不行啊 ,下载也挂了. 下载了700个就好了一天,上传没成过.

**Comment by bingsanyu** [comment]
感谢反馈 :sparkling_heart:

- 上传
  - 批量上传没有测试过，已在README中说明。
  - 单个上传确实会报错 :cry:，原因是请求标头中的*referer*参数要求为*minutes.feishu.cn*。已更新代码，请您clone后重新尝试。

- 下载
  - 多个会议下载时的速度主要卡在字幕下载，考完研后我会尝试进行解决。
  - 如果下载速度峰值未达到您的带宽最大下载速度，请尝试更换DNS。

如有更多信息请提供 :wave:

**Comment by jcfangc** [comment]
好厉害啊，我成功了，想请教一下怎么学习这方面的知识呀？是web后端吗？

**Comment by bingsanyu** [comment]
@jcfangc 我也是初学者，不敢以己昏昏使人昭昭。web后端略显庞杂，你可以先找找爬虫相关的博客。
