### ISSUE TITLE
请教开发方法

### ISSUE THREAD

**Issue by jcfangc** [bingsanyu/feishu_minutes#7]
hi，前两天跟据你的回复，我恶补了一下网络抓包，学跟着你的代码尝试自己写一个版本，但是我遇到了关于token的问题，源于你在`FeishuUploader`的构造函数中编写了这样一个请求头：

```python
        self.headers = {
            "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
            "cookie": cookie,
            "bv-csrf-token": cookie[
                cookie.find("bv_csrf_token=")
                + len("bv_csrf_token=") : cookie.find(
                    ";", cookie.find("bv_csrf_token=")
                )
            ],
            "referer": "https://minutes.feishu.cn/minutes/home",
        }
```

让我疑惑的时这里token的选择，因为我在开发者工具中返回的cookie中还看到了很多不一样的token：_csrf_token, lgw_csrf_token, csrf_token, swp_csrf_token，你选择bv-csrf-token有什么理由吗？

希望得到你的指点！谢谢！

**Comment by bingsanyu** [comment]
![image](https://github.com/bingsanyu/feishu_minutes/assets/66949416/25c6a64e-f6c5-4b0a-8aad-11ecc6d1b517)

网络请求复现流程：先将所抓到的包的请求头中的参数（除了以`:`开头的伪头部字段）全部写入代码中的请求头参数中，然后注释掉部分参数，仍能成功返回结果就删除这些参数，直到所有的参数都是此请求所必需的。

此请求头中：
- `user-agent`：用于伪装成浏览器，写爬虫时一般都要带上。
- `bv-csrf-token`、`cookie`、`referer`三个是必需参数。其中`bv-csrf-token`包含在`cookie`中，所以不必再要求用户复制该参数，而是选择从cookie中获取。

cookie没有进一步拆分的必要，因为其中键值对的意义难以明确，**能用就行**。

**Comment by jcfangc** [comment]
感谢解答！！
